#!/usr/bin/env bash

SCENARIO_ARRAY=(
  # "1pod-diffnode-sidecar-1core-default"
  # "1pod-diffnode-sidecar-1core-4conc-tuned"
  # "1pod-diffnode-sidecar-1core-6conc-tuned"
  # "1pod-diffnode-sidecar-1core-8conc-tuned"
  # "1pod-diffnode-sidecar-1core-tuned"
  # "1pod-diffnode-sidecar-2core-4conc-tuned"
  # "1pod-diffnode-sidecar-2core-6conc-tuned"
  # "1pod-diffnode-sidecar-2core-8conc-tuned"
  # "1pod-diffnode-sidecar-2core-tuned"
  # "1pod-diffnode-sidecar-3core-4conc-tuned"
  # "1pod-diffnode-sidecar-3core-6conc-tuned"
  # "1pod-diffnode-sidecar-3core-8conc-tuned"
  # "1pod-diffnode-sidecar-3core-tuned"
  # "1pod-diffnode-sidecar-mtls-1core-4conc-tuned"
  # "1pod-diffnode-sidecar-mtls-1core-6conc-tuned"
  # "1pod-diffnode-sidecar-mtls-1core-8conc-tuned"
  "1pod-diffnode-sidecar-mtls-1core-tuned"
  "1pod-diffnode-sidecar-mtls-2core-4conc-tuned"
  "1pod-diffnode-sidecar-mtls-2core-6conc-tuned"
  "1pod-diffnode-sidecar-mtls-2core-8conc-tuned"
  "1pod-diffnode-sidecar-mtls-2core-tuned"
  "1pod-diffnode-sidecar-mtls-3core-4conc-tuned"
  "1pod-diffnode-sidecar-mtls-3core-6conc-tuned"
  "1pod-diffnode-sidecar-mtls-3core-8conc-tuned"
  "1pod-diffnode-sidecar-mtls-3core-tuned"
  "1pod-diffnode-sidecarclient-1core-4conc-tuned"
  "1pod-diffnode-sidecarclient-1core-6conc-tuned"
  "1pod-diffnode-sidecarclient-1core-8conc-tuned"
  "1pod-diffnode-sidecarclient-1core-tuned"
  "1pod-diffnode-sidecarclient-2core-tuned"
  "1pod-diffnode-sidecarclient-3core-tuned"
  "1pod-diffnode-sidecarserver-1core-4conc-tuned"
  "1pod-diffnode-sidecarserver-1core-6conc-tuned"
  "1pod-diffnode-sidecarserver-1core-8conc-tuned"
  "1pod-diffnode-sidecarserver-1core-tuned"
  "1pod-diffnode-sidecarserver-2core-tuned"
  "1pod-diffnode-sidecarserver-3core-tuned"
  "1pod-samenode-sidecar-1core-4conc-tuned"
  "1pod-samenode-sidecar-1core-6conc-tuned"
  "1pod-samenode-sidecar-1core-8conc-tuned"
  "1pod-samenode-sidecar-1core-tuned"
  "1pod-samenode-sidecar-2core-4conc-tuned"
  "1pod-samenode-sidecar-2core-6conc-tuned"
  "1pod-samenode-sidecar-2core-8conc-tuned"
  "1pod-samenode-sidecar-2core-tuned"
  "1pod-samenode-sidecar-3core-4conc-tuned"
  "1pod-samenode-sidecar-3core-6conc-tuned"
  "1pod-samenode-sidecar-3core-8conc-tuned"
  "1pod-samenode-sidecar-3core-tuned"
  "1pod-samenode-sidecar-mtls-1core-4conc-tuned"
  "1pod-samenode-sidecar-mtls-1core-6conc-tuned"
  "1pod-samenode-sidecar-mtls-1core-8conc-tuned"
  "1pod-samenode-sidecar-mtls-1core-tuned"
  "1pod-samenode-sidecar-mtls-2core-4conc-tuned"
  "1pod-samenode-sidecar-mtls-2core-6conc-tuned"
  "1pod-samenode-sidecar-mtls-2core-8conc-tuned"
  "1pod-samenode-sidecar-mtls-2core-tuned"
  "1pod-samenode-sidecar-mtls-3core-4conc-tuned"
  "1pod-samenode-sidecar-mtls-3core-6conc-tuned"
  "1pod-samenode-sidecar-mtls-3core-8conc-tuned"
  "1pod-samenode-sidecar-mtls-3core-tuned"
  "1pod-samenode-sidecarclient-1core-4conc-tuned"
  "1pod-samenode-sidecarclient-1core-6conc-tuned"
  "1pod-samenode-sidecarclient-1core-8conc-tuned"
  "1pod-samenode-sidecarclient-1core-tuned"
  "1pod-samenode-sidecarclient-2core-tuned"
  "1pod-samenode-sidecarclient-3core-tuned"
  "1pod-samenode-sidecarserver-1core-4conc-tuned"
  "1pod-samenode-sidecarserver-1core-6conc-tuned"
  "1pod-samenode-sidecarserver-1core-8conc-tuned"
  "1pod-samenode-sidecarserver-1core-tuned"
  "1pod-samenode-sidecarserver-2core-tuned"
  "1pod-samenode-sidecarserver-3core-tuned"
  "2pod-diffnode-sidecar-1core-tuned"
  "2pod-diffnode-sidecar-mtls-1core-tuned"
  "2pod-samenode-sidecar-1core-tuned"
  "2pod-samenode-sidecar-mtls-1core-tuned"
  "3pod-diffnode-sidecar-1core-tuned"
  "3pod-diffnode-sidecar-mtls-1core-tuned"
  "3pod-samenode-sidecar-1core-tuned"
  "3pod-samenode-sidecar-mtls-1core-tuned"
)

for SCENARIO in "${SCENARIO_ARRAY[@]}" ; do

  make uninstall-client uninstall-server delete-namespace 
  sleep 20
  make create-namespace install-client install-server SCENARIO=${SCENARIO}
  sleep 20
  make wait-ready

  ./find_concurreny_max_qps.sh -l ${SCENARIO} -t 1m

done
